/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apresentacao;

import DAL.MedicoDAO;
import DAL.PacienteDAO;
import javax.swing.JOptionPane;
import modelo.Paciente;
import servico.ServicoAutenticacao;

/**
 *
 * @author Admin
 */
public class TelaMedico extends javax.swing.JFrame {

    /**
     * Creates new form TelaMedico
     */
    public TelaMedico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmExibirGeral = new javax.swing.JFrame();
        jTabExibirDadosLinha = new javax.swing.JScrollPane();
        TblDados = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();
        btnAvancar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnPesquisarPorNome = new javax.swing.JButton();
        txfNomePesquisado = new javax.swing.JTextField();
        frmPesquisar = new javax.swing.JFrame();
        btnPesquisarPorCPF = new javax.swing.JButton();
        txfCpf = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();
        frmRegistros = new javax.swing.JFrame();
        btnNovoRegistro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        frmCPFPaciente = new javax.swing.JFrame();
        lblCpf1 = new javax.swing.JLabel();
        txfCpfParaRegistro = new javax.swing.JTextField();
        btnContinuarComRegistro = new javax.swing.JButton();
        jMenu = new javax.swing.JMenuBar();
        jMenuSobreMim = new javax.swing.JMenu();
        jMenuMeusDados = new javax.swing.JMenuItem();
        jMenuPacientes = new javax.swing.JMenu();
        JMExibirTodosPacientes = new javax.swing.JMenuItem();
        JMPacientePesquisarCPF = new javax.swing.JMenuItem();
        jMenuRegistrosMeusPacientes = new javax.swing.JMenuItem();

        frmExibirGeral.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabExibirDadosLinha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabExibirDadosLinhaMouseClicked(evt);
            }
        });

        TblDados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TblDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome Completo", "Usuario", "CPF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TblDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblDadosMouseClicked(evt);
            }
        });
        jTabExibirDadosLinha.setViewportView(TblDados);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnAvancar.setText("Avançar");
        btnAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancarActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Clique duas vezes para abrir mais informações");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnPesquisarPorNome.setText("Pesquisar por Nome");
        btnPesquisarPorNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarPorNomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmExibirGeralLayout = new javax.swing.GroupLayout(frmExibirGeral.getContentPane());
        frmExibirGeral.getContentPane().setLayout(frmExibirGeralLayout);
        frmExibirGeralLayout.setHorizontalGroup(
            frmExibirGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabExibirDadosLinha, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
            .addGroup(frmExibirGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frmExibirGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmExibirGeralLayout.createSequentialGroup()
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAvancar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frmExibirGeralLayout.createSequentialGroup()
                        .addComponent(txfNomePesquisado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisarPorNome)))
                .addContainerGap())
        );
        frmExibirGeralLayout.setVerticalGroup(
            frmExibirGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmExibirGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frmExibirGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPesquisarPorNome, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(txfNomePesquisado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabExibirDadosLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frmExibirGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(frmExibirGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(btnAvancar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        frmPesquisar.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        frmPesquisar.setTitle("Pesquisar");

        btnPesquisarPorCPF.setText("Pesquisar");
        btnPesquisarPorCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarPorCPFActionPerformed(evt);
            }
        });

        lblCpf.setText("Digite o CPF:");

        javax.swing.GroupLayout frmPesquisarLayout = new javax.swing.GroupLayout(frmPesquisar.getContentPane());
        frmPesquisar.getContentPane().setLayout(frmPesquisarLayout);
        frmPesquisarLayout.setHorizontalGroup(
            frmPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmPesquisarLayout.createSequentialGroup()
                .addGroup(frmPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmPesquisarLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(txfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frmPesquisarLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(lblCpf))
                    .addGroup(frmPesquisarLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(btnPesquisarPorCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        frmPesquisarLayout.setVerticalGroup(
            frmPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmPesquisarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblCpf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(txfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPesquisarPorCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        btnNovoRegistro.setText("Novo Registro");
        btnNovoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoRegistroActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout frmRegistrosLayout = new javax.swing.GroupLayout(frmRegistros.getContentPane());
        frmRegistros.getContentPane().setLayout(frmRegistrosLayout);
        frmRegistrosLayout.setHorizontalGroup(
            frmRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(frmRegistrosLayout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(btnNovoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frmRegistrosLayout.setVerticalGroup(
            frmRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmRegistrosLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNovoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        lblCpf1.setText("Digite o CPF:");

        btnContinuarComRegistro.setText("Continuar");
        btnContinuarComRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarComRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmCPFPacienteLayout = new javax.swing.GroupLayout(frmCPFPaciente.getContentPane());
        frmCPFPaciente.getContentPane().setLayout(frmCPFPacienteLayout);
        frmCPFPacienteLayout.setHorizontalGroup(
            frmCPFPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmCPFPacienteLayout.createSequentialGroup()
                .addGroup(frmCPFPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmCPFPacienteLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(txfCpfParaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frmCPFPacienteLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(lblCpf1))
                    .addGroup(frmCPFPacienteLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(btnContinuarComRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        frmCPFPacienteLayout.setVerticalGroup(
            frmCPFPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmCPFPacienteLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblCpf1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(txfCpfParaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnContinuarComRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuSobreMim.setText("Sobre Mim");
        jMenuSobreMim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSobreMimActionPerformed(evt);
            }
        });

        jMenuMeusDados.setText("Meus Dados");
        jMenuSobreMim.add(jMenuMeusDados);

        jMenu.add(jMenuSobreMim);

        jMenuPacientes.setText("Pacientes");

        JMExibirTodosPacientes.setText("Meus Pacientes");
        jMenuPacientes.add(JMExibirTodosPacientes);

        JMPacientePesquisarCPF.setText("Pesquisar CPF");
        jMenuPacientes.add(JMPacientePesquisarCPF);

        jMenuRegistrosMeusPacientes.setText("Registros");
        jMenuPacientes.add(jMenuRegistrosMeusPacientes);

        jMenu.add(jMenuPacientes);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSobreMimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSobreMimActionPerformed

    }//GEN-LAST:event_jMenuSobreMimActionPerformed

    private void TblDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblDadosMouseClicked

    }//GEN-LAST:event_TblDadosMouseClicked

    private void jTabExibirDadosLinhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabExibirDadosLinhaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabExibirDadosLinhaMouseClicked

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed

    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancarActionPerformed

    }//GEN-LAST:event_btnAvancarActionPerformed

    private void btnPesquisarPorNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarPorNomeActionPerformed

    }//GEN-LAST:event_btnPesquisarPorNomeActionPerformed

    private void btnPesquisarPorCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarPorCPFActionPerformed

    }//GEN-LAST:event_btnPesquisarPorCPFActionPerformed

    private void btnNovoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoRegistroActionPerformed
        frmCPFPaciente.setVisible(true);
        frmCPFPaciente.setLocationRelativeTo(null);
        frmCPFPaciente.dispose();
    }//GEN-LAST:event_btnNovoRegistroActionPerformed

    private void btnContinuarComRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarComRegistroActionPerformed
        String cpfPaciente = txfCpfParaRegistro.getText().trim(); // Obtém o CPF do paciente digitado

// Obtém o nome do médico logado
        ServicoAutenticacao servicoAutenticacao = new ServicoAutenticacao();
        String nomeMedicoLogado = servicoAutenticacao.getNomeCompletoLogado();

// Verificando se o CPF do paciente existe no banco de dados
        PacienteDAO pacienteDAO = new PacienteDAO();
        Paciente paciente = pacienteDAO.obterPacietePorCPF(cpfPaciente);

        if (paciente == null) {
            // Se o CPF do paciente não for encontrado, mostra uma mensagem de erro
            JOptionPane.showMessageDialog(null, "CPF do paciente não encontrado. Verifique e tente novamente.");
        } else {
            // Se o CPF for encontrado, abre a tela de cadastro de registro
            TelaCadastroRegistro telaCadastroRegistro = new TelaCadastroRegistro();

            // Preenche os campos da tela de registro com os dados do paciente e do médico
            telaCadastroRegistro.getTxfNomePaciente().setText(paciente.getNome()); // Preenche com o nome do paciente
            telaCadastroRegistro.getTxfNomeMedico().setText(nomeMedicoLogado); // Preenche com o nome do médico

            // Torna a tela de cadastro de registro visível
            telaCadastroRegistro.setVisible(true);
            telaCadastroRegistro.setLocationRelativeTo(null); // Centraliza a tela
        }
    }//GEN-LAST:event_btnContinuarComRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMExibirTodosPacientes;
    private javax.swing.JMenuItem JMPacientePesquisarCPF;
    private javax.swing.JTable TblDados;
    private javax.swing.JButton btnAvancar;
    private javax.swing.JButton btnContinuarComRegistro;
    private javax.swing.JButton btnNovoRegistro;
    private javax.swing.JButton btnPesquisarPorCPF;
    private javax.swing.JButton btnPesquisarPorNome;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JFrame frmCPFPaciente;
    private javax.swing.JFrame frmExibirGeral;
    private javax.swing.JFrame frmPesquisar;
    private javax.swing.JFrame frmRegistros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JMenuItem jMenuMeusDados;
    private javax.swing.JMenu jMenuPacientes;
    private javax.swing.JMenuItem jMenuRegistrosMeusPacientes;
    private javax.swing.JMenu jMenuSobreMim;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jTabExibirDadosLinha;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblCpf1;
    private javax.swing.JTextField txfCpf;
    private javax.swing.JTextField txfCpfParaRegistro;
    private javax.swing.JTextField txfNomePesquisado;
    // End of variables declaration//GEN-END:variables
}
