/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apresentacao.medico;

import DAL.MedicoDAO;
import DAL.PacienteDAO;
import DAL.RegistroDAO;
import apresentacao.TelaCadastroRegistro;
import apresentacao.medico.TelaVisualizarDadosMedico;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Medico;
import modelo.Paciente;
import modelo.Registro;
import servico.ServicoAutenticacao;
import servico.ServicoUsuarioLogado;

/**
 *
 * @author Admin
 */
public class TelaMedico extends javax.swing.JFrame {

    private DefaultTableModel tableModel;
    private int paginaAtual = 1;
    private static final int ITENS_POR_PAGINA = 20;

    /**
     * Creates new form TelaMedico
     */
    public TelaMedico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmPesquisar = new javax.swing.JFrame();
        btnPesquisarPorCPF = new javax.swing.JButton();
        txfCpf = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();
        frmRegistros = new javax.swing.JFrame();
        btnNovoRegistro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDados = new javax.swing.JTable();
        txfNomePesquisado = new javax.swing.JTextField();
        btnPesquisarPorNome = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnAvancar = new javax.swing.JButton();
        frmCPFPaciente = new javax.swing.JFrame();
        lblCpf1 = new javax.swing.JLabel();
        txfCpfParaRegistro = new javax.swing.JTextField();
        btnContinuarComRegistro = new javax.swing.JButton();
        jMenu = new javax.swing.JMenuBar();
        jMenuSobreMim = new javax.swing.JMenu();
        jMenuMeusDados = new javax.swing.JMenuItem();
        jMenuPacientes = new javax.swing.JMenu();
        JMExibirTodosPacientes = new javax.swing.JMenuItem();
        JMPacientePesquisarCPF = new javax.swing.JMenuItem();
        jMenuRegistrosMeusPacientes = new javax.swing.JMenuItem();

        frmPesquisar.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        frmPesquisar.setTitle("Pesquisar");

        btnPesquisarPorCPF.setText("Pesquisar");
        btnPesquisarPorCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarPorCPFActionPerformed(evt);
            }
        });

        lblCpf.setText("Digite o CPF:");

        javax.swing.GroupLayout frmPesquisarLayout = new javax.swing.GroupLayout(frmPesquisar.getContentPane());
        frmPesquisar.getContentPane().setLayout(frmPesquisarLayout);
        frmPesquisarLayout.setHorizontalGroup(
            frmPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmPesquisarLayout.createSequentialGroup()
                .addGroup(frmPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmPesquisarLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(txfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frmPesquisarLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(lblCpf))
                    .addGroup(frmPesquisarLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(btnPesquisarPorCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        frmPesquisarLayout.setVerticalGroup(
            frmPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmPesquisarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblCpf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(txfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPesquisarPorCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        btnNovoRegistro.setText("Novo Registro");
        btnNovoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoRegistroActionPerformed(evt);
            }
        });

        tblDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Descrição", "Medico", "Paciente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDados);
        if (tblDados.getColumnModel().getColumnCount() > 0) {
            tblDados.getColumnModel().getColumn(0).setResizable(false);
            tblDados.getColumnModel().getColumn(1).setResizable(false);
            tblDados.getColumnModel().getColumn(2).setResizable(false);
        }

        btnPesquisarPorNome.setText("Pesquisar por Nome");
        btnPesquisarPorNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarPorNomeActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnAvancar.setText("Avançar");
        btnAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmRegistrosLayout = new javax.swing.GroupLayout(frmRegistros.getContentPane());
        frmRegistros.getContentPane().setLayout(frmRegistrosLayout);
        frmRegistrosLayout.setHorizontalGroup(
            frmRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmRegistrosLayout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(btnNovoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(332, Short.MAX_VALUE))
            .addGroup(frmRegistrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(frmRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(frmRegistrosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(frmRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(frmRegistrosLayout.createSequentialGroup()
                            .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(557, 557, 557)
                            .addComponent(btnAvancar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(frmRegistrosLayout.createSequentialGroup()
                            .addComponent(txfNomePesquisado)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnPesquisarPorNome)))
                    .addContainerGap()))
        );
        frmRegistrosLayout.setVerticalGroup(
            frmRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmRegistrosLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNovoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(frmRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(frmRegistrosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(frmRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnPesquisarPorNome, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                        .addComponent(txfNomePesquisado))
                    .addGap(451, 451, 451)
                    .addGroup(frmRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAvancar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        lblCpf1.setText("Digite o CPF:");

        btnContinuarComRegistro.setText("Continuar");
        btnContinuarComRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarComRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmCPFPacienteLayout = new javax.swing.GroupLayout(frmCPFPaciente.getContentPane());
        frmCPFPaciente.getContentPane().setLayout(frmCPFPacienteLayout);
        frmCPFPacienteLayout.setHorizontalGroup(
            frmCPFPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmCPFPacienteLayout.createSequentialGroup()
                .addGroup(frmCPFPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmCPFPacienteLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(txfCpfParaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frmCPFPacienteLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(lblCpf1))
                    .addGroup(frmCPFPacienteLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(btnContinuarComRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        frmCPFPacienteLayout.setVerticalGroup(
            frmCPFPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmCPFPacienteLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblCpf1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(txfCpfParaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnContinuarComRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jMenuSobreMim.setText("Sobre Mim");
        jMenuSobreMim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSobreMimActionPerformed(evt);
            }
        });

        jMenuMeusDados.setText("Meus Dados");
        jMenuMeusDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMeusDadosActionPerformed(evt);
            }
        });
        jMenuSobreMim.add(jMenuMeusDados);

        jMenu.add(jMenuSobreMim);

        jMenuPacientes.setText("Pacientes");

        JMExibirTodosPacientes.setText("Meus Pacientes");
        JMExibirTodosPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMExibirTodosPacientesActionPerformed(evt);
            }
        });
        jMenuPacientes.add(JMExibirTodosPacientes);

        JMPacientePesquisarCPF.setText("Pesquisar CPF");
        JMPacientePesquisarCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMPacientePesquisarCPFActionPerformed(evt);
            }
        });
        jMenuPacientes.add(JMPacientePesquisarCPF);

        jMenuRegistrosMeusPacientes.setText("Registros");
        jMenuRegistrosMeusPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRegistrosMeusPacientesActionPerformed(evt);
            }
        });
        jMenuPacientes.add(jMenuRegistrosMeusPacientes);

        jMenu.add(jMenuPacientes);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSobreMimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSobreMimActionPerformed

    }//GEN-LAST:event_jMenuSobreMimActionPerformed

    private void btnPesquisarPorCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarPorCPFActionPerformed

    }//GEN-LAST:event_btnPesquisarPorCPFActionPerformed

    private void btnNovoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoRegistroActionPerformed
        frmCPFPaciente.setVisible(true);
        frmCPFPaciente.setLocationRelativeTo(null);
        frmCPFPaciente.setSize(305, 190);
    }//GEN-LAST:event_btnNovoRegistroActionPerformed

    private void btnContinuarComRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarComRegistroActionPerformed
        try {
            String cpfPaciente = txfCpfParaRegistro.getText();
            String nomeMedicoLogado = ServicoUsuarioLogado.getInstance().getNomeCompleto();

            PacienteDAO pacienteDAO = new PacienteDAO();
            Paciente paciente = pacienteDAO.obterPacietePorCPF(cpfPaciente);

            if (paciente == null) {
                JOptionPane.showMessageDialog(null, "CPF do paciente não encontrado. Verifique e tente novamente.");
            } else {
                TelaCadastroRegistro telaCadastroRegistro = new TelaCadastroRegistro();
                telaCadastroRegistro.getTxfNomePaciente().setText(paciente.getNomeCompleto());
                telaCadastroRegistro.getTxfNomeMedico().setText(nomeMedicoLogado);
                telaCadastroRegistro.setVisible(true);
                telaCadastroRegistro.setLocationRelativeTo(null);
            }
        } catch (Exception e) {
            e.printStackTrace(); // Exibe o erro no console
            JOptionPane.showMessageDialog(null, "Ocorreu um erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btnContinuarComRegistroActionPerformed

    private void jMenuRegistrosMeusPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRegistrosMeusPacientesActionPerformed
        frmRegistros.setVisible(true);
        frmRegistros.setLocationRelativeTo(null);
        frmRegistros.setSize(750, 595);
        carregarPagina(1, 20);
    }//GEN-LAST:event_jMenuRegistrosMeusPacientesActionPerformed

    private void btnPesquisarPorNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarPorNomeActionPerformed
        RegistroDAO registroDAO = new RegistroDAO();
        String nomePesquisado = txfNomePesquisado.getText(); // Obtém o texto do campo de pesquisa

        if (!nomePesquisado.trim().isEmpty()) {
            List<Registro> registrosFiltrados = registroDAO.buscarPorNomePaciente(nomePesquisado);
            atualizarTabela(registrosFiltrados); // Atualiza a tabela com os registros filtrados
        } else {
            // Se o campo estiver vazio, carrega a tabela normalmente
            carregarPagina(paginaAtual, ITENS_POR_PAGINA);
        }
    }//GEN-LAST:event_btnPesquisarPorNomeActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        if (paginaAtual > 1) {
            paginaAtual--;
            carregarPagina(paginaAtual, ITENS_POR_PAGINA); // Carrega a página anterior
        }
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancarActionPerformed
        RegistroDAO registroDAO = new RegistroDAO();
        long totalRegistros = registroDAO.contarTotalRegistros(); // Conta o total de registros
        int totalPaginas = (int) Math.ceil((double) totalRegistros / ITENS_POR_PAGINA); // Calcula o número total de páginas

        if (paginaAtual < totalPaginas) { // Só avança se ainda houver páginas
            paginaAtual++;
            carregarPagina(paginaAtual, ITENS_POR_PAGINA); // Carrega a próxima página
        }
    }//GEN-LAST:event_btnAvancarActionPerformed

    private void jMenuMeusDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMeusDadosActionPerformed
        TelaVisualizarDadosMedico telaVisualizarDadosMedico = new TelaVisualizarDadosMedico();
        telaVisualizarDadosMedico.setVisible(true);
        telaVisualizarDadosMedico.setLocationRelativeTo(null);

        ServicoUsuarioLogado usuarioLogado = ServicoUsuarioLogado.getInstance();

        if ("Medico".equals(usuarioLogado.getTipo())) {
            // Realiza uma busca no banco de dados para obter os detalhes completos do médico logado
            MedicoDAO medicoDAO = new MedicoDAO();
            Medico medico = medicoDAO.buscarPorId(usuarioLogado.getId());

            // Preenche os campos da tela com os dados do médico logado
            if (medico != null) {
                telaVisualizarDadosMedico.getTxfNome().setText(medico.getNomeCompleto());
                telaVisualizarDadosMedico.getTxfUsuario().setText(medico.getNomeUsuario());
                telaVisualizarDadosMedico.getTxfCpf().setText(medico.getCpf());
                telaVisualizarDadosMedico.getTxfNascimento().setText(medico.getDataNascimento());
                // Outros campos que você quiser preencher
            }
        }
    }//GEN-LAST:event_jMenuMeusDadosActionPerformed

    private void JMExibirTodosPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMExibirTodosPacientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMExibirTodosPacientesActionPerformed

    private void JMPacientePesquisarCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMPacientePesquisarCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMPacientePesquisarCPFActionPerformed

    public void atualizarTabela(List<Registro> registros) {
        DefaultTableModel modelo = (DefaultTableModel) tblDados.getModel();
        modelo.setRowCount(0); // Limpa a tabela

        for (Registro registro : registros) {
            modelo.addRow(new Object[]{
                registro.getPaciente().getNomeCompleto(), // Nome do paciente
                registro.getMedico().getNomeCompleto(), // Nome do médico responsável
                registro.getDescricao() // Descrição do registro
            });

        }
    }

    private void carregarPagina(int paginaAtual, int linhasPorPagina) {
        DefaultTableModel modelo = (DefaultTableModel) tblDados.getModel();
        modelo.setRowCount(0); // Limpa a tabela antes de carregar novos dados

        RegistroDAO registroDAO = new RegistroDAO();
        List<Registro> registros = registroDAO.carregarPagina(paginaAtual, linhasPorPagina);

        // Verifica se a lista de registros não está vazia antes de iterar
        if (registros != null && !registros.isEmpty()) {
            for (Registro registro : registros) {
                String nomePaciente = (registro.getPaciente() != null) ? registro.getPaciente().getNomeCompleto() : "Desconhecido";
                String nomeMedico = (registro.getMedico() != null) ? registro.getMedico().getNomeCompleto() : "Desconhecido";
                String descricao = (registro.getDescricao() != null) ? registro.getDescricao() : "Sem descrição";

                Object[] dados = {
                    nomePaciente, // Nome do paciente
                    nomeMedico, // Nome do médico
                    descricao // Descrição do registro
                };
                modelo.addRow(dados);
            }
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMExibirTodosPacientes;
    private javax.swing.JMenuItem JMPacientePesquisarCPF;
    private javax.swing.JButton btnAvancar;
    private javax.swing.JButton btnContinuarComRegistro;
    private javax.swing.JButton btnNovoRegistro;
    private javax.swing.JButton btnPesquisarPorCPF;
    private javax.swing.JButton btnPesquisarPorNome;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JFrame frmCPFPaciente;
    private javax.swing.JFrame frmPesquisar;
    private javax.swing.JFrame frmRegistros;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JMenuItem jMenuMeusDados;
    private javax.swing.JMenu jMenuPacientes;
    private javax.swing.JMenuItem jMenuRegistrosMeusPacientes;
    private javax.swing.JMenu jMenuSobreMim;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblCpf1;
    private javax.swing.JTable tblDados;
    private javax.swing.JTextField txfCpf;
    private javax.swing.JTextField txfCpfParaRegistro;
    private javax.swing.JTextField txfNomePesquisado;
    // End of variables declaration//GEN-END:variables
}
